package com.asomepig.finance.model;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.catName
     *
     * @mbggenerated
     */
    private String catname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.catInfo
     *
     * @mbggenerated
     */
    private String catinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.catName
     *
     * @return the value of category.catName
     *
     * @mbggenerated
     */
    public String getCatname() {
        return catname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.catName
     *
     * @param catname the value for category.catName
     *
     * @mbggenerated
     */
    public void setCatname(String catname) {
        this.catname = catname == null ? null : catname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.catInfo
     *
     * @return the value of category.catInfo
     *
     * @mbggenerated
     */
    public String getCatinfo() {
        return catinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.catInfo
     *
     * @param catinfo the value for category.catInfo
     *
     * @mbggenerated
     */
    public void setCatinfo(String catinfo) {
        this.catinfo = catinfo == null ? null : catinfo.trim();
    }
}