package com.asomepig.finance.IDao;

import com.asomepig.finance.model.Muchmoney;

public interface MuchmoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table muchmoney
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table muchmoney
     *
     * @mbggenerated
     */
    int insert(Muchmoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table muchmoney
     *
     * @mbggenerated
     */
    int insertSelective(Muchmoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table muchmoney
     *
     * @mbggenerated
     */
    Muchmoney selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table muchmoney
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Muchmoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table muchmoney
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Muchmoney record);
}